[package]
name = "mp_lang"
version = "0.1.0"
edition = "2024"

[lib]
name = "mp_lang"
path = "src/lib.rs"

[[bin]]
name = "mp"
path = "src/main.rs"

[dependencies]
rustyline = { version = "16.0.0", features = ["derive"] }
