let a = 10
let b = 20
let result = a > b
print("a > b:", result)

result = a < b
print("a < b:", result)

result = a == b
print("a == b:", result)

result = a != b
print("a != b:", result)

result = a >= b
print("a >= b:", result)

result = a <= b
print("a <= b:", result)

let x = 5
let y = 10
let z = 15
print("Logical operations:")
print((x < y) && (y < z))
print((x > 100) || (y < 20))
print((!false))
